return {
	"neovim/nvim-lspconfig",
	-- dependencies = { "saghen/blink.cmp" },
	-- config = function()
	-- 	local capabilities = {
	-- 		textDocument = {
	-- 			foldingRange = {
	-- 				dynamicRegistration = false,
	-- 				lineFoldingOnly = true,
	-- 			},
	-- 		},
	-- 	}
	--
	-- 	capabilities = require("blink.cmp").get_lsp_capabilities(capabilities)
	--
	-- 	-- or equivalently
	--
	-- 	local capabilities = vim.lsp.protocol.make_client_capabilities()
	--
	-- 	capabilities = vim.tbl_deep_extend("force", capabilities, require("blink.cmp").get_lsp_capabilities({}, false))
	--
	-- 	capabilities = vim.tbl_deep_extend("force", capabilities, {
	-- 		textDocument = {
	-- 			foldingRange = {
	-- 				dynamicRegistration = false,
	-- 				lineFoldingOnly = true,
	-- 			},
	-- 		},
	-- 	})
	-- end,
}
