-- require('jedplugins.packer')
require("jedplugins.lazy")
require("jedplugins.telescope")
require("jedplugins.onedark")
require("jedplugins.treesitter")
require("jedplugins.fugitive")
require("jedplugins.gitsigns")
require("jedplugins.indentblankline")
require("jedplugins.nvimcomment")
require("jedplugins.nvimsurround")
require("jedplugins.nvimautopairs")
require("jedplugins.hop")
require("jedplugins.lualine")
require("jedplugins.undotree")
require("jedplugins.nvimtree")
require("jedplugins.webdevicons")
require("jedplugins.lsp")
require("jedplugins.dap")
require("jedplugins.bufferline")
require("jedplugins.notify")
require("jedplugins.fidget")
require("jedplugins.barbecue")
require("jedplugins.marks")
require("jedplugins.ngswitcher")

require("jedplugins.debug_adapters")
